(cl:defpackage position_control_cpp-srv
  (:use )
  (:export
   "SET_POSITION"
   "<SET_POSITION-REQUEST>"
   "SET_POSITION-REQUEST"
   "<SET_POSITION-RESPONSE>"
   "SET_POSITION-RESPONSE"
   "SET_VELOCITY"
   "<SET_VELOCITY-REQUEST>"
   "SET_VELOCITY-REQUEST"
   "<SET_VELOCITY-RESPONSE>"
   "SET_VELOCITY-RESPONSE"
  ))

