// Generated by gencpp from file position_control_cpp/set_position.msg
// DO NOT EDIT!


#ifndef POSITION_CONTROL_CPP_MESSAGE_SET_POSITION_H
#define POSITION_CONTROL_CPP_MESSAGE_SET_POSITION_H

#include <ros/service_traits.h>


#include <position_control_cpp/set_positionRequest.h>
#include <position_control_cpp/set_positionResponse.h>


namespace position_control_cpp
{

struct set_position
{

typedef set_positionRequest Request;
typedef set_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_position
} // namespace position_control_cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::position_control_cpp::set_position > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::position_control_cpp::set_position&) { return value(); }
};

template<>
struct DataType< ::position_control_cpp::set_position > {
  static const char* value()
  {
    return "position_control_cpp/set_position";
  }

  static const char* value(const ::position_control_cpp::set_position&) { return value(); }
};


// service_traits::MD5Sum< ::position_control_cpp::set_positionRequest> should match
// service_traits::MD5Sum< ::position_control_cpp::set_position >
template<>
struct MD5Sum< ::position_control_cpp::set_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::position_control_cpp::set_position >::value();
  }
  static const char* value(const ::position_control_cpp::set_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::position_control_cpp::set_positionRequest> should match
// service_traits::DataType< ::position_control_cpp::set_position >
template<>
struct DataType< ::position_control_cpp::set_positionRequest>
{
  static const char* value()
  {
    return DataType< ::position_control_cpp::set_position >::value();
  }
  static const char* value(const ::position_control_cpp::set_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::position_control_cpp::set_positionResponse> should match
// service_traits::MD5Sum< ::position_control_cpp::set_position >
template<>
struct MD5Sum< ::position_control_cpp::set_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::position_control_cpp::set_position >::value();
  }
  static const char* value(const ::position_control_cpp::set_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::position_control_cpp::set_positionResponse> should match
// service_traits::DataType< ::position_control_cpp::set_position >
template<>
struct DataType< ::position_control_cpp::set_positionResponse>
{
  static const char* value()
  {
    return DataType< ::position_control_cpp::set_position >::value();
  }
  static const char* value(const ::position_control_cpp::set_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSITION_CONTROL_CPP_MESSAGE_SET_POSITION_H
