// Generated by gencpp from file position_control_cpp/set_velocity.msg
// DO NOT EDIT!


#ifndef POSITION_CONTROL_CPP_MESSAGE_SET_VELOCITY_H
#define POSITION_CONTROL_CPP_MESSAGE_SET_VELOCITY_H

#include <ros/service_traits.h>


#include <position_control_cpp/set_velocityRequest.h>
#include <position_control_cpp/set_velocityResponse.h>


namespace position_control_cpp
{

struct set_velocity
{

typedef set_velocityRequest Request;
typedef set_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_velocity
} // namespace position_control_cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::position_control_cpp::set_velocity > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::position_control_cpp::set_velocity&) { return value(); }
};

template<>
struct DataType< ::position_control_cpp::set_velocity > {
  static const char* value()
  {
    return "position_control_cpp/set_velocity";
  }

  static const char* value(const ::position_control_cpp::set_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::position_control_cpp::set_velocityRequest> should match
// service_traits::MD5Sum< ::position_control_cpp::set_velocity >
template<>
struct MD5Sum< ::position_control_cpp::set_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::position_control_cpp::set_velocity >::value();
  }
  static const char* value(const ::position_control_cpp::set_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::position_control_cpp::set_velocityRequest> should match
// service_traits::DataType< ::position_control_cpp::set_velocity >
template<>
struct DataType< ::position_control_cpp::set_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::position_control_cpp::set_velocity >::value();
  }
  static const char* value(const ::position_control_cpp::set_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::position_control_cpp::set_velocityResponse> should match
// service_traits::MD5Sum< ::position_control_cpp::set_velocity >
template<>
struct MD5Sum< ::position_control_cpp::set_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::position_control_cpp::set_velocity >::value();
  }
  static const char* value(const ::position_control_cpp::set_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::position_control_cpp::set_velocityResponse> should match
// service_traits::DataType< ::position_control_cpp::set_velocity >
template<>
struct DataType< ::position_control_cpp::set_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::position_control_cpp::set_velocity >::value();
  }
  static const char* value(const ::position_control_cpp::set_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSITION_CONTROL_CPP_MESSAGE_SET_VELOCITY_H
